### ISSUE TITLE
STEP or F3D files possible to make available?

### ISSUE THREAD

**Issue by ccatlett1984** [eleclab-rpi/10INCH_HDMI_DISPLAY#1]
I appreciate the STL files, but I need to modify the case in order to enclose another pcb as well, would it be possible to release a STEP or f3d file of the case?

**Comment by eleclab-rpi** [comment]
Great, please tell me the corresponding file name and I will upload the step file on GitHub.
 
From: ccatlett1984
Date: 2024-10-10 12:25
To: eleclab-rpi/10INCH_HDMI_DISPLAY
CC: Subscribed
Subject: [eleclab-rpi/10INCH_HDMI_DISPLAY] STEP or F3D files possible to make available? (Issue #1)
I appreciate the STL files, but I need to modify the case in order to enclose another pcb as well, would it be possible to release a STEP or f3d file of the case?

**Comment by ccatlett1984** [comment]
10.1INCH_2560x1600_Case2_RPI.STL

**Comment by eleclab-rpi** [comment]
HI, 10.1INCH_2560x1600_Case2_RPI.STEP has been uploaded to https://github.com/eleclab-rpi/10INCH_HDMI_DISPLAY

From: ccatlett1984
Date: 2024-10-10 14:08
To: eleclab-rpi/10INCH_HDMI_DISPLAY
CC: ElecLab; Comment
Subject: Re: [eleclab-rpi/10INCH_HDMI_DISPLAY] STEP or F3D files possible to make available? (Issue #1)
10.1INCH_2560x1600_Case2_RPI.STL
